require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MineralTestsController do

  # This should return the minimal set of attributes required to create a valid
  # MineralTest. As you add validations to MineralTest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "water_source" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MineralTestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mineral_tests as @mineral_tests" do
      mineral_test = MineralTest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mineral_tests).should eq([mineral_test])
    end
  end

  describe "GET show" do
    it "assigns the requested mineral_test as @mineral_test" do
      mineral_test = MineralTest.create! valid_attributes
      get :show, {:id => mineral_test.to_param}, valid_session
      assigns(:mineral_test).should eq(mineral_test)
    end
  end

  describe "GET new" do
    it "assigns a new mineral_test as @mineral_test" do
      get :new, {}, valid_session
      assigns(:mineral_test).should be_a_new(MineralTest)
    end
  end

  describe "GET edit" do
    it "assigns the requested mineral_test as @mineral_test" do
      mineral_test = MineralTest.create! valid_attributes
      get :edit, {:id => mineral_test.to_param}, valid_session
      assigns(:mineral_test).should eq(mineral_test)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MineralTest" do
        expect {
          post :create, {:mineral_test => valid_attributes}, valid_session
        }.to change(MineralTest, :count).by(1)
      end

      it "assigns a newly created mineral_test as @mineral_test" do
        post :create, {:mineral_test => valid_attributes}, valid_session
        assigns(:mineral_test).should be_a(MineralTest)
        assigns(:mineral_test).should be_persisted
      end

      it "redirects to the created mineral_test" do
        post :create, {:mineral_test => valid_attributes}, valid_session
        response.should redirect_to(MineralTest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mineral_test as @mineral_test" do
        # Trigger the behavior that occurs when invalid params are submitted
        MineralTest.any_instance.stub(:save).and_return(false)
        post :create, {:mineral_test => { "water_source" => "invalid value" }}, valid_session
        assigns(:mineral_test).should be_a_new(MineralTest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MineralTest.any_instance.stub(:save).and_return(false)
        post :create, {:mineral_test => { "water_source" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mineral_test" do
        mineral_test = MineralTest.create! valid_attributes
        # Assuming there are no other mineral_tests in the database, this
        # specifies that the MineralTest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MineralTest.any_instance.should_receive(:update).with({ "water_source" => "" })
        put :update, {:id => mineral_test.to_param, :mineral_test => { "water_source" => "" }}, valid_session
      end

      it "assigns the requested mineral_test as @mineral_test" do
        mineral_test = MineralTest.create! valid_attributes
        put :update, {:id => mineral_test.to_param, :mineral_test => valid_attributes}, valid_session
        assigns(:mineral_test).should eq(mineral_test)
      end

      it "redirects to the mineral_test" do
        mineral_test = MineralTest.create! valid_attributes
        put :update, {:id => mineral_test.to_param, :mineral_test => valid_attributes}, valid_session
        response.should redirect_to(mineral_test)
      end
    end

    describe "with invalid params" do
      it "assigns the mineral_test as @mineral_test" do
        mineral_test = MineralTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MineralTest.any_instance.stub(:save).and_return(false)
        put :update, {:id => mineral_test.to_param, :mineral_test => { "water_source" => "invalid value" }}, valid_session
        assigns(:mineral_test).should eq(mineral_test)
      end

      it "re-renders the 'edit' template" do
        mineral_test = MineralTest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MineralTest.any_instance.stub(:save).and_return(false)
        put :update, {:id => mineral_test.to_param, :mineral_test => { "water_source" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mineral_test" do
      mineral_test = MineralTest.create! valid_attributes
      expect {
        delete :destroy, {:id => mineral_test.to_param}, valid_session
      }.to change(MineralTest, :count).by(-1)
    end

    it "redirects to the mineral_tests list" do
      mineral_test = MineralTest.create! valid_attributes
      delete :destroy, {:id => mineral_test.to_param}, valid_session
      response.should redirect_to(mineral_tests_url)
    end
  end

end
