require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TreatmentChemicalsController do

  # This should return the minimal set of attributes required to create a valid
  # TreatmentChemical. As you add validations to TreatmentChemical, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TreatmentChemicalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all treatment_chemicals as @treatment_chemicals" do
      treatment_chemical = TreatmentChemical.create! valid_attributes
      get :index, {}, valid_session
      assigns(:treatment_chemicals).should eq([treatment_chemical])
    end
  end

  describe "GET show" do
    it "assigns the requested treatment_chemical as @treatment_chemical" do
      treatment_chemical = TreatmentChemical.create! valid_attributes
      get :show, {:id => treatment_chemical.to_param}, valid_session
      assigns(:treatment_chemical).should eq(treatment_chemical)
    end
  end

  describe "GET new" do
    it "assigns a new treatment_chemical as @treatment_chemical" do
      get :new, {}, valid_session
      assigns(:treatment_chemical).should be_a_new(TreatmentChemical)
    end
  end

  describe "GET edit" do
    it "assigns the requested treatment_chemical as @treatment_chemical" do
      treatment_chemical = TreatmentChemical.create! valid_attributes
      get :edit, {:id => treatment_chemical.to_param}, valid_session
      assigns(:treatment_chemical).should eq(treatment_chemical)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TreatmentChemical" do
        expect {
          post :create, {:treatment_chemical => valid_attributes}, valid_session
        }.to change(TreatmentChemical, :count).by(1)
      end

      it "assigns a newly created treatment_chemical as @treatment_chemical" do
        post :create, {:treatment_chemical => valid_attributes}, valid_session
        assigns(:treatment_chemical).should be_a(TreatmentChemical)
        assigns(:treatment_chemical).should be_persisted
      end

      it "redirects to the created treatment_chemical" do
        post :create, {:treatment_chemical => valid_attributes}, valid_session
        response.should redirect_to(TreatmentChemical.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved treatment_chemical as @treatment_chemical" do
        # Trigger the behavior that occurs when invalid params are submitted
        TreatmentChemical.any_instance.stub(:save).and_return(false)
        post :create, {:treatment_chemical => { "name" => "invalid value" }}, valid_session
        assigns(:treatment_chemical).should be_a_new(TreatmentChemical)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TreatmentChemical.any_instance.stub(:save).and_return(false)
        post :create, {:treatment_chemical => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested treatment_chemical" do
        treatment_chemical = TreatmentChemical.create! valid_attributes
        # Assuming there are no other treatment_chemicals in the database, this
        # specifies that the TreatmentChemical created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TreatmentChemical.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => treatment_chemical.to_param, :treatment_chemical => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested treatment_chemical as @treatment_chemical" do
        treatment_chemical = TreatmentChemical.create! valid_attributes
        put :update, {:id => treatment_chemical.to_param, :treatment_chemical => valid_attributes}, valid_session
        assigns(:treatment_chemical).should eq(treatment_chemical)
      end

      it "redirects to the treatment_chemical" do
        treatment_chemical = TreatmentChemical.create! valid_attributes
        put :update, {:id => treatment_chemical.to_param, :treatment_chemical => valid_attributes}, valid_session
        response.should redirect_to(treatment_chemical)
      end
    end

    describe "with invalid params" do
      it "assigns the treatment_chemical as @treatment_chemical" do
        treatment_chemical = TreatmentChemical.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TreatmentChemical.any_instance.stub(:save).and_return(false)
        put :update, {:id => treatment_chemical.to_param, :treatment_chemical => { "name" => "invalid value" }}, valid_session
        assigns(:treatment_chemical).should eq(treatment_chemical)
      end

      it "re-renders the 'edit' template" do
        treatment_chemical = TreatmentChemical.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TreatmentChemical.any_instance.stub(:save).and_return(false)
        put :update, {:id => treatment_chemical.to_param, :treatment_chemical => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested treatment_chemical" do
      treatment_chemical = TreatmentChemical.create! valid_attributes
      expect {
        delete :destroy, {:id => treatment_chemical.to_param}, valid_session
      }.to change(TreatmentChemical, :count).by(-1)
    end

    it "redirects to the treatment_chemicals list" do
      treatment_chemical = TreatmentChemical.create! valid_attributes
      delete :destroy, {:id => treatment_chemical.to_param}, valid_session
      response.should redirect_to(treatment_chemicals_url)
    end
  end

end
